version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=toor
         - POSTGRES_USER=postgres
         - POSTGRES_DB=postgres
  frontend:
    image: frontend:latest
    container_name: frontend-container
    ports:
      - 4200:80
  backend:
    image: backend:latest
    container_name: backend
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: toor
    depends_on:
      - postgres